### ISSUE TITLE
Issue with missing icons 

### ISSUE THREAD

**Issue by RailsCod3rFuture** [tomkra/font_awesome5_rails#26]
It seems that this gem clashes with other gems that use the old syntax for font-awesome. Test the 'wysiwyg-rails' gem (froala) for further inspection. Is there anyway to keep compatibility issues to a bare minimum? I tried to put @import "font-awesome" and "font-awesome-sprockets" above  @import "font-awesome5" but certain icons are missing on the froalaEditor interface. 

Thanks

**Comment by tomkra** [comment]
@RailsCod3rFuture Well I've been digging into this and there should be no compatibility issues with this gem. Is it working for you, when you remove ```@import "font_awesome5"``` from your ```application.scss```?

Problem is that **wysiwyg-rails** gem have specified dependency for **font-awesome-sass** gem which will install latest version of gem with FA5 included. But froala editor works only with FA4 ([link](https://www.froala.com/wysiwyg-editor/docs/overview)), so that can cause the problem. I think that there is opened issue for this on **wysiwyg-rails** gem github check [#64 issue](https://github.com/froala/wysiwyg-rails/issues/64)

**Comment by tomkra** [comment]
@RailsCod3rFuture Ok, I will close the issue for now. Feel free to reopen if there will be any incompability issues with this gem in future or just create new issue.
