### ISSUE TITLE
Icons not generated properly

### ISSUE THREAD

**Issue by Fabstilelook** [tomkra/font_awesome5_rails#38]
If I type for example:

`= fa_icon('youtube', type: :fab)`

The result I get is:

`<i type="fab" class="fa fa-youtube"></i>`

While, reading from the documentation, the result should be:

`<i class="fab fa-youtube"></i>`

I also have gem 'font-awesome-rails', '~> 4.4.0' installed. So I wonder if the issue is some conflict with that gem.

**Comment by tomkra** [comment]
@Fabstilelook Hello, definitelly issue comes from conflict with ```font-awesome-rails```, because in this gem I'm using the same method helper name ```fa_icon```. We have tests for the example you mentioned, so I'm sure It's working correctly. Problem is that ```fa_icon``` method called is executed from ```font-awesome-rails``` gem and from ours so you get icon generated for older version of font.

If you want to use both gems simultaneously, you can try this:
``` = fab_icon('youtube')```
This method is not present in ```font-awesome-rails``` gem so It should call right method from this gem and you can ommit type specification. Check Readme for use ```far, fas, fab``` helper methods.

Hope this helps.

**Comment by Fabstilelook** [comment]
@tomkra I'm also using the gem `rails_admin` and it seems it has a dependency with `font-awesome-rails` that's why I would like to keep them both. I've tried your suggestion:

`= fab_icon('youtube')`

but this still prints out:

`<i type="fab" class="fa fa-youtube"></i>`

instead of: 

`<i class="fab fa-youtube"></i>`

**Comment by tomkra** [comment]
@Fabstilelook I've tried use both gems simultaneously and I had difficulties you've described. So I've added new ```fa5_icon``` and ```fa5_stacked_icon``` method aliases.

Please update to last version of gem to ```0.7.0```. After that you will be able to use font awesome 5 icons by calling these methods. Since they are not present in original ```font-awesome-rails``` gem, they will be called from right gem and proper method icon generator will be used.

Please try this solution and let me know, if it worked.

**Comment by Fabstilelook** [comment]
@tomkra great thank you very much! it's working now with version `0.7.0` and using the method `fa5_icon`
