### ISSUE TITLE
facebook / twitter icons not working

### ISSUE THREAD

**Issue by masterkain** [tomkra/font_awesome5_rails#51]
hello,
I have this problem,

it seems everything is working but the brand icons

`= fa_icon 'twitter'`
`= fa_icon 'facebook'`

will show the question mark

imported with 

```
gem 'font_awesome5_rails', '~> 1.0'

//= require font_awesome5

@import "font_awesome5.css";
```

![Screenshot 2020-02-09 at 14 34 46](https://user-images.githubusercontent.com/12844/74103067-5b056f00-4b49-11ea-8429-24c195887bee.png)

**Comment by tomkra** [comment]
Hey @masterkain, these icons are brand icons so you have to call helper like this to genereate appropriate FontAwesome [class](https://fontawesome.com/icons/twitter?style=brands):

```ruby
= fa_icon 'twitter', type: :brand
```
or
```ruby
= fab_icon 'twitter'
```

Check the documentation for [examples](https://github.com/tomkra/font_awesome5_rails#solid-regular-light-brand-icon-types). It's because for brand icons needs to be generated different class than for regular.

Hope this helps.

**Comment by masterkain** [comment]
thanks, I'll try 👍
